### ISSUE TITLE
bdep.exe --help prints out a stackdump from less.exe on windows 10.

### ISSUE THREAD

**Issue by jonesmz** [build2/build2#141]
bdep.exe --help
      0 [main] less 1922 less.exe: *** fatal error - cmalloc would have returned NULL
    355 [main] less 1922 cygwin_exception::open_stackdumpfile: Dumping stack trace to less.exe.stackdump

**Comment by Klaim** [comment]
I cannot reproduce this issue either:

On Windows 10.0.19043 Build 19043 (I just updated):

- with `build2` v0.13.0 built last year with MSVC (not sure which version exactly): can't reproduce the issue in either git-bash or Powershell;
- with a fresh stage install of `v0.14.0` built with VS16.10.3 : cannot reproduce either with either Powershell or git-bash.

Note that I use git-bash based on `cmd` (option in the installer), not the cygwin version which for me has always be problematic. Maybe try with just `cmd` or `Powershell`/`Windows Terminal` ?

**Comment by boris-kolpackov** [comment]
Turns out `bdep --help` doesn't have any fancy (UTF-8) `tree` output (but other help topics, like `new` used to have,  which is now fixed). I've also re-tested on FreeBSD 13.0 and both `bdep --help` and `bdep help new` work as expected with the latest staged toolchain. So the original report is probably something else.

**Comment by boris-kolpackov** [comment]
@Klaim Do you think you can try `bdep.exe --help` one more time on your current setup (maybe on both Windows 10 and 11, if you have access)? Thanks!

**Comment by Klaim** [comment]
Of course.
However, so far I still can't manage to reproduce it.
I'm on Windows 11 right now, I tried with `v0.14.0` and stage (`bdep 0.15.0-a.0.ed05ed4c87df`), with `cmd`, `powershell`, `git-bash` based on `cmd`, and I also installed a separate cygwin to try in there. Every `bdep --help` works as expected.

I'll try again on Windows 10 on my laptop when I find the time.

I didn't try yet to use an install of `build2` with the scripts based on mingw and clang, maybe that changes something, but it will take some time to try that.

@jonesmz Can you still reproduce the issue today? Which `build2` install script did you use?
